[miniflux_pi]
raspberrypi.local ansible_user=admin miniflux_target=pi

[miniflux_gcp]
miniflux ansible_host=miniflux ansible_user=jasonroc19_gmail_com miniflux_target=gcp

[miniflux_vm:children]
miniflux_pi
miniflux_gcp
