[miniflux_gcp]
miniflux ansible_host=miniflux.us-west1-b.miniflux-494022 ansible_user=jasonroc19_gmail_com ansible_python_interpreter=/usr/bin/python3 ansible_ssh_extra_args="-o ProxyCommand='gcloud compute start-iap-tunnel miniflux 22 --listen-on-stdin --project=miniflux-494022 --zone=us-west1-b'"
