site_name: rocjay1 Infrastructure Docs
site_url: https://docs.roccosmodernsite.net/rocjay1-infrastructure/
repo_url: https://github.com/rocjay1/rocjay1-infrastructure
repo_name: rocjay1-infrastructure

nav:
  - Home: index.md
  - Workspaces:
    - Ansible: ansible.md
    - Cloudflare: cloudflare.md
    - FlareBridge: flare-bridge.md
    - Google Cloud: google-cloud.md
    - Miniflux: miniflux.md

extra:
  homepage: https://docs.roccosmodernsite.net/

theme:
  name: material
  palette:
    primary: emerald
    accent: emerald
  font:
    text: Segoe UI
    code: Roboto Mono

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
