---
# Default Docker daemon configuration (suitable for Raspberry Pi / standard Debian)
debian_docker_host_docker_daemon_config:
  log-driver: "json-file"
  log-opts:
    max-size: "10m"
    max-file: "3"
