name: Terraform Validate

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        workspace:
          - miniflux/terraform
          - cloudflare/terraform
          - flare-bridge/terraform

    defaults:
      run:
        working-directory: ${{ matrix.workspace }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Format Check
        working-directory: .
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false -input=false

      - name: Terraform Validate
        run: terraform validate
